spring:
  application:
    name: blogdulich

  data:
    mongodb:
      uri: mongodb://localhost:27017/BlogDuLich


jwt:
  signerKey: "23U00bRSGRL2gaiemios4RWzqK7zkefptW0ssg3XvEaud/1yOe3XulNtS/+NaRPG"

defaultImage:
  avartar: "https://res.cloudinary.com/desoarfu8/image/upload/v1759670502/samples/man-portrait.jpg"

cloudinary:
  cloud-name: your_cloud_name
  api-key: your_api_key
  api-secret: your_api_secret